services:
  - type: web
    name: gnuh-kang-ih
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATA_DIR
        value: /var/data
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
